# Generated by Django 3.0.5 on 2021-01-29 20:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EquipementSportif', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Historique',
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
        migrations.DeleteModel(
            name='Professeur',
        ),
        migrations.DeleteModel(
            name='ProfilUser',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='activite',
            old_name='age',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='equipement',
            old_name='name',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='etablissement',
            old_name='name',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='etudiant',
            old_name='name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='ligneactivite',
            old_name='age',
            new_name='quantite',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='name',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='age',
        ),
        migrations.RemoveField(
            model_name='etablissement',
            name='age',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='age',
        ),
        migrations.RemoveField(
            model_name='ligneactivite',
            name='name',
        ),
        migrations.AddField(
            model_name='activite',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activite',
            name='etudiant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EquipementSportif.Etudiant'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='intitule',
            field=models.CharField(default=None, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etablissement',
            name='intitule',
            field=models.CharField(default=None, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etablissement',
            name='region',
            field=models.CharField(default=None, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etablissement',
            name='ville',
            field=models.CharField(default=None, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='etablissement',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EquipementSportif.Etablissement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='nom',
            field=models.CharField(default=None, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='premon',
            field=models.CharField(default=None, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ligneactivite',
            name='Activite',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EquipementSportif.Activite'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ligneactivite',
            name='Equipement',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EquipementSportif.Equipement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ligneactivite',
            name='date_debut_emprunt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ligneactivite',
            name='date_fin_emprunt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ligneactivite',
            name='date_restitution',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ligneactivite',
            name='statut',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='Etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EquipementSportif.Etablissement'),
        ),
        migrations.AddField(
            model_name='stock',
            name='equipement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EquipementSportif.Equipement'),
        ),
    ]
