# Generated by Django 3.1.5 on 2021-01-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EquipementSportif', '0002_auto_20210129_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='id',
        ),
        migrations.RemoveField(
            model_name='etablissement',
            name='id',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='id',
        ),
        migrations.AlterField(
            model_name='equipement',
            name='code',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='code',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(max_length=80),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
