# Generated by Django 3.1.5 on 2021-01-29 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EquipementSportif', '0003_auto_20210129_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='etablissement',
        ),
    ]
